/* Autogenerated by /usr/bin/halcompile on Sun Apr 12 17:05:36 2026 -- do not edit */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "rtapi_math64.h"

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:dropjet:Dropjet controller");
MODULE_INFO(linuxcnc, "pin:pulse_width:float:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:pulse_hz:float:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:single_dot:u32:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:multi_dot:bit:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:dj_pin:bit:0:out::None:None");
MODULE_INFO(linuxcnc, "funct:_:1:");
MODULE_INFO(linuxcnc, "license:GPL");
MODULE_INFO(linuxcnc, "author:Erik Friesen");
MODULE_LICENSE("GPL");
#endif // MODULE_INFO

struct __comp_state
{
    struct __comp_state *_next;
    hal_float_t *pulse_width;
    hal_float_t *pulse_hz;
    hal_u32_t *single_dot;
    hal_bit_t *multi_dot;
    hal_bit_t *dj_pin;
    int first;
};
struct __comp_state *__comp_first_inst = 0, *__comp_last_inst = 0;

static void _(struct __comp_state *__comp_inst, long period);
static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg)
{
    char buf[HAL_NAME_LEN + 1];
    int r = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);
    r = hal_pin_float_newf(HAL_IN, &(inst->pulse_width), comp_id,
                           "%s.pulse-width", prefix);
    if (r != 0)
        return r;
    r = hal_pin_float_newf(HAL_IN, &(inst->pulse_hz), comp_id,
                           "%s.pulse-hz", prefix);
    if (r != 0)
        return r;
    r = hal_pin_u32_newf(HAL_IN, &(inst->single_dot), comp_id,
                         "%s.single-dot", prefix);
    if (r != 0)
        return r;
    r = hal_pin_bit_newf(HAL_IN, &(inst->multi_dot), comp_id,
                         "%s.multi-dot", prefix);
    if (r != 0)
        return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->dj_pin), comp_id,
                         "%s.dj-pin", prefix);
    if (r != 0)
        return r;
    rtapi_snprintf(buf, sizeof(buf), "%s", prefix);
    r = hal_export_funct(buf, (void (*)(void *inst, long))_, inst, 1, 0, comp_id);
    if (r != 0)
        return r;
    if (__comp_last_inst)
        __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if (!__comp_first_inst)
        __comp_first_inst = inst;
    return 0;
}
static int default_count = 1, count = 0;
RTAPI_MP_INT(count, "number of dropjet");
char *names = ""; // comma separated names
RTAPI_MP_STRING(names, "names of dropjet");
int rtapi_app_main(void)
{
    int r = 0;
    int i;
    comp_id = hal_init("dropjet");
    if (comp_id < 0)
        return comp_id;
    if (count && names[0])
    {
        rtapi_print_msg(RTAPI_MSG_ERR, "count= and names= are mutually exclusive\n");
        return -EINVAL;
    }
    if (!count && !names[0])
        count = default_count;
    if (count)
    {
        for (i = 0; i < count; i++)
        {
            char buf[HAL_NAME_LEN + 1];
            rtapi_snprintf(buf, sizeof(buf), "dropjet.%d", i);
            r = export(buf, i);
            if (r != 0)
                break;
        }
    }
    else
    {
        size_t i, j;
        int idx;
        char buf[HAL_NAME_LEN + 1];
        const size_t length = strlen(names);
        for (i = j = idx = 0; i <= length; i++)
        {
            const char c = buf[j] = names[i];
            if ((c == ',') || (c == '\0'))
            {
                buf[j] = '\0';
                r = export(buf, idx);
                if (r != 0)
                {
                    break;
                }
                idx++;
                j = 0;
            }
            else
            {
                if (++j == (sizeof(buf) / sizeof(buf[0])))
                {
                    buf[j - 1] = '\0';
                    rtapi_print_msg(RTAPI_MSG_ERR, "names: \"%s\" too long\n", buf);
                    r = -EINVAL;
                    break;
                }
            }
        }
    }
    if (r)
    {
        hal_exit(comp_id);
    }
    else
    {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void)
{
    hal_exit(comp_id);
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef fperiod
#define fperiod (period * 1e-9)
#undef pulse_width
#define pulse_width (0 + *__comp_inst->pulse_width)
#undef pulse_hz
#define pulse_hz (0 + *__comp_inst->pulse_hz)
#undef single_dot
#define single_dot (0 + *__comp_inst->single_dot)
#undef multi_dot
#define multi_dot (0 + *__comp_inst->multi_dot)
#undef dj_pin
#define dj_pin (*__comp_inst->dj_pin)
#undef first
#define first (__comp_inst->first)

#line 15 "dropjet.comp"

FUNCTION(_)
{
    if (!first)
    {
        first = 1;
        rtapi_print_msg(RTAPI_MSG_INFO, "Starting DJ controller\n");
    }
    dj_pin = single_dot > 0;
}
static int __comp_get_data_size(void) { return 0; }
